### ISSUE TITLE
TextPushButton 和OutlinePushButton 组件点击就崩溃 

### ISSUE THREAD

**Issue by wenvelope** [zhiyiYo/QMaterialWidgets#18]
**Describe the bug**
点击按钮后
Process finished with exit code -1073740791 (0xC0000409)

**Environment**
环境信息
- OS: [e.g. Windows11]

**To Reproduce**
1. 运行项目
2. 点击按钮
3. 程序结束 Process finished with exit code -1073740791 (0xC0000409)

**Code**
最小复现代码
```python
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 760)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DisplayLabel = DisplayLabel(parent=self.centralwidget)
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.verticalLayout.addWidget(self.DisplayLabel)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.TextPushButton = TextPushButton(parent=self.centralwidget)
        self.TextPushButton.setCheckable(False)
        self.TextPushButton.setAutoDefault(False)
        self.TextPushButton.setObjectName("TextPushButton")
        self.verticalLayout.addWidget(self.TextPushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DisplayLabel.setText(_translate("MainWindow", "Display label"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.TextPushButton.setText(_translate("MainWindow", "Text push button"))
from qmaterialwidgets import DisplayLabel, TextPushButton


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.TextPushButton.clicked.connect(lambda: print("323"))

if __name__ == '__main__':
    app = QApplication([])
    window = MainWindow()
    window.show()
    app.exec()

```

**Comment by wenvelope** [comment]
看了一下报错位置
D:\miniconda3\envs\Qt6Develope\python.exe D:\PycharmProjects\QtDemo\src\Main.py 
Traceback (most recent call last):
  File "D:\miniconda3\envs\Qt6Develope\lib\site-packages\qmaterialwidgets\components\widgets\ripple.py", line 177, in paintEvent
    self._drawRipple(painter, ripple)
  File "D:\miniconda3\envs\Qt6Develope\lib\site-packages\qmaterialwidgets\components\widgets\ripple.py", line 182, in _drawRipple
    painter.drawEllipse(ripple.center, ripple.radius, ripple.radius)
TypeError: arguments did not match any overloaded call:
  drawEllipse(self, r: QRectF): argument 1 has unexpected type 'QPoint'
  drawEllipse(self, r: QRect): argument 1 has unexpected type 'QPoint'
  drawEllipse(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'QPoint'
  drawEllipse(self, center: QPointF, rx: float, ry: float): argument 1 has unexpected type 'QPoint'
  drawEllipse(self, center: QPoint, rx: int, ry: int): argument 2 has unexpected type 'float'
