### ISSUE TITLE
gallery demo 报错

### ISSUE THREAD

**Issue by tom9672** [zhiyiYo/QMaterialWidgets#5]
button demo 不报错。

gallery demo 报错:
```
(pyside6_material) C:\Users\Administrator\Desktop\fluent_demo\QMaterialWidgets-master\examples\gallery>python demo.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\fluent_demo\QMaterialWidgets-master\examples\gallery\demo.py", line 11, in <module>
    from app.view.main_window import MainWindow
  File "C:\Users\Administrator\Desktop\fluent_demo\QMaterialWidgets-master\examples\gallery\app\view\main_window.py", line 6, in <module>
    from qmaterialwidgets import (NavigationItemPosition, MaterialWindow, SplashScreen, Theme,
ImportError: cannot import name 'NavigationItemPosition' from 'qmaterialwidgets' (C:\Users\Administrator\.conda\envs\pyside6_material\lib\site-packages\qmaterialwidgets\__init__.py)
```

pip list:
```
(pyside6_material) C:\Users\Administrator\Desktop\fluent_demo\QMaterialWidgets-master\examples\gallery>pip list
Package                    Version
-------------------------- ---------
asttokens                  2.2.1
backcall                   0.2.0
click                      8.1.6
colorama                   0.4.6
comm                       0.1.3
darkdetect                 0.8.0
debugpy                    1.6.7
decorator                  5.1.1
executing                  1.2.0
importlib-metadata         6.7.0
ipykernel                  6.23.3
ipython                    8.14.0
jedi                       0.18.2
jupyter_client             8.3.0
jupyter_core               5.3.1
matplotlib-inline          0.1.6
nest-asyncio               1.5.6
parso                      0.8.3
pickleshare                0.7.5
pip                        23.2.1
platformdirs               3.8.0
prompt-toolkit             3.0.38
pure-eval                  0.2.2
Pygments                   2.15.1
PyQt6                      6.4.2
pyqt6-plugins              6.4.2.2.3
PyQt6-Qt6                  6.4.3
PyQt6-sip                  13.5.2
pyqt6-tools                6.4.2.3.3
PySide6                    6.4.2
PySide6-Addons             6.4.2
PySide6-Essentials         6.4.2
PySide6-Material-Widgets   0.0.2
PySideSix-Frameless-Window 0.1.1
python-dotenv              1.0.0
pywin32                    306
pyzmq                      25.1.0
qt6-applications           6.4.3.2.3
qt6-tools                  6.4.3.1.3
setuptools                 68.0.0
shiboken6                  6.4.2
stack-data                 0.6.2
tornado                    6.3.2
traitlets                  5.9.0
typing_extensions          4.6.3
wcwidth                    0.2.6
wheel                      0.38.4
```

**Comment by zhiyiYo** [comment]
看readme
